### ISSUE TITLE
Vuejs.org VuePress Migration Feedback

### ISSUE THREAD

**Issue by bencodezen** [softvenue/contribution-guide#2]
Hi @Aissaoui-Ahmed and @celyes! My name is Ben Hong and I'm a Vue.js Community Partner that is currently working with the Vue.js Core Docs Team to help with updating the platform from Hexo to VuePress. During this time, we plan to have a content freeze in order to ensure all of the sites stay in sync with one another.

As maintainers for the Arabic translation site, are there any pain points or concerns that you might have about this migration? We would love to hear from you and make sure your thoughts are taken into consideration before starting work on this.

Looking forward to your response!

P.S. My apologies for creating an issue in this repo. I was unable to create an Issue in the translation repo directly and felt this was the most generic location to do so.

**Comment by celyes** [comment]
Thank you @bencodezen for your message.
Currently, We don't have any concerns as maintainers and we're totally good with the migration process.
Thank you!
@Aissaoui-Ahmed
